<?php
$webtitle="vivi百度影音";
$url="/bdyyxt/";
$erji="";
$tongji="";
$beian="京ICP证030173号";
$cache="off";
$imgcache="off";
$indexcache="10";
$listcache="8";
$htmlcache="24";
$playcache="24";
$delcache="30";
$wyc="on";
$rewrite="off";
$caiji='curl_init';
$mulu="l/";
$news="p/";
$playc="f/";
$keywords="最新电影,最新连续剧,百度影音电影";
$description="欢迎来到百度影音电影院，这里有最新电影，最新连续剧，百度影音电影..我们支持vivi小偷程序";
$flink="";
$template="default";
?>